name: barriers_old
channels:
  - pytorch
  - conda-forge
  - defaults
  - omnia
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - aom=3.3.0=h27087fc_1
  - ase=3.22.1=pyhd8ed1ab_1
  - asgiref=3.5.2=pyhd8ed1ab_0
  - asttokens=2.0.5=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=2.106=mkl
  - boost=1.74.0=py39h5472131_5
  - boost-cpp=1.74.0=h75c5d50_8
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py39hb9d737c_1004
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.6.15=ha878542_0
  - cairo=1.16.0=ha61ee94_1011
  - certifi=2022.6.15=py39hf3d152e_0
  - cffi=1.15.0=py39h4bc2ebd_0
  - cftime=1.6.0=py39hd257fcd_1
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - click=8.1.3=py39hf3d152e_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - crest=2.12=h9d67668_0
  - cryptography=37.0.1=py39h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - curl=7.83.1=h2283fc2_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cython=0.29.30=py39h5a03fae_0
  - debugpy=1.6.0=py39h5a03fae_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - django=4.0=pyhd8ed1ab_0
  - django-filter=2.4.0=py_0
  - django-guardian=2.4.0=pyhd8ed1ab_0
  - djangorestframework=3.12.4=pyhd8ed1ab_0
  - djangorestframework-csv=2.1.1=pyhd8ed1ab_0
  - docutils=0.18.1=py39hf3d152e_1
  - double-conversion=3.2.0=h9c3ff4c_0
  - eigen=3.4.0=h4bd325d_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.8.3=pyhd8ed1ab_0
  - expat=2.4.8=h27087fc_0
  - ffmpeg=4.4.1=h964e5f1_4
  - flask=2.1.2=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.10.4=h0708190_1
  - future=0.18.2=py39hf3d152e_5
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h36c2ea0_2
  - gl2ps=1.4.2=h0708190_0
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py39h78fa15d_0
  - gnutls=3.6.13=h85f3911_1
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.12.1=nompi_h4df4325_104
  - icu=70.1=h27087fc_0
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py39hf3d152e_0
  - importlib_metadata=4.11.4=hd8ed1ab_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - ipython=8.3.0=py39hf3d152e_0
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jedi=0.18.1=py39hf3d152e_1
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jmespath=0.10.0=pyh9f0ad1d_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_1
  - jsoncpp=1.9.5=h4bd325d_1
  - jupyter_client=7.3.1=pyhd8ed1ab_0
  - jupyter_core=4.10.0=py39hf3d152e_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.2=py39hf939315_1
  - krb5=1.19.3=h08a2579_0
  - lame=3.100=h7f98852_1001
  - latexcodec=2.0.1=pyh9f0ad1d_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=6_mkl
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=6_mkl
  - libcurl=7.83.1=h2283fc2_0
  - libdeflate=1.10=h7f98852_0
  - libdrm=2.4.109=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libglib=2.70.2=h174f98d_4
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=6_mkl
  - liblapacke=3.9.0=6_mkl
  - libnetcdf=4.8.1=nompi_h329d8a1_102
  - libnghttp2=1.47.0=he49606f_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libpciaccess=0.16=h516909a_0
  - libpng=1.6.37=h21135ba_2
  - libpq=13.5=h676c864_1
  - libprotobuf=3.16.0=h780b84a_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=ha35d2d1_2
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtheora=1.1.1=h7f98852_1005
  - libtiff=4.3.0=h0fcbabc_4
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.43.0=h7f98852_0
  - libva=2.14.0=h7f98852_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.14=h22db469_0
  - libzip=1.8.0=h1c5bbd1_1
  - libzlib=1.2.11=h166bdaf_1014
  - llvm-openmp=14.0.4=he0ac6c6_0
  - loguru=0.6.0=py39hf3d152e_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.1.1=py39hb9d737c_1
  - matplotlib-base=3.4.3=py39h2fa2bec_2
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mctc-lib=0.3.0=hc3ea6d6_0
  - mkl=2020.4=h726a3e6_304
  - monty=2022.4.26=pyhd8ed1ab_0
  - more-itertools=8.13.0=pyhd8ed1ab_0
  - mpc=1.2.1=h9f54685_0
  - mpfr=4.1.0=h9202a9a_1
  - mpmath=1.2.1=pyhd8ed1ab_0
  - munch=2.5.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nb_conda_kernels=2.3.1=py39hf3d152e_1
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - netcdf4=1.5.8=nompi_py39h64b754b_101
  - nettle=3.6=he412f7d_0
  - networkx=2.7.1=pyhd8ed1ab_0
  - ninja=1.11.0=h924138e_0
  - numpy=1.22.4=py39hc58783e_0
  - oniguruma=6.9.8=h166bdaf_0
  - openbabel=3.1.1=py39hee2736e_3
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.0.5=h166bdaf_0
  - packaging=21.3=pyhd8ed1ab_0
  - palettable=3.3.0=py_0
  - pandas=1.4.2=py39h1832856_2
  - parallel=20220522=ha770c72_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - perl=5.32.1=2_h7f98852_perl5
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.1.1=py39hae2aec6_0
  - pip=22.1.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - plotly=5.8.0=pyhd8ed1ab_1
  - pluggy=1.0.0=py39hf3d152e_3
  - proj=9.0.0=h93bde94_1
  - prompt-toolkit=3.0.29=pyha770c72_0
  - psycopg2=2.9.2=py39h3811e60_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pugixml=1.11.4=h9c3ff4c_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py=1.10.0=pyhd3deb0d_0
  - pybtex=0.24.0=pyhd8ed1ab_2
  - pycairo=1.21.0=py39h0934665_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.12.0=pyhd8ed1ab_0
  - pymatgen=2022.5.26=py39hf939315_0
  - pymongo=4.1.1=py39h5a03fae_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=py39hf3d152e_5
  - pytest=7.1.2=py39hf3d152e_0
  - python=3.9.12=h2660328_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=1.11.0=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.1=pyhd8ed1ab_0
  - pyyaml=6.0=py39hb9d737c_4
  - pyzmq=23.0.0=py39headdf64_0
  - rdkit=2020.09.1=py39h54e287e_0
  - readline=8.1=h46c0cb4_0
  - requests=2.27.1=pyhd8ed1ab_0
  - ruamel.yaml=0.17.21=py39hb9d737c_1
  - ruamel.yaml.clib=0.2.6=py39hb9d737c_1
  - scikit-learn=1.1.1=py39h4037b75_0
  - scipy=1.8.1=py39he49c0e8_0
  - setuptools=62.3.2=py39hf3d152e_0
  - simplegeneric=0.8.1=py_1
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h9b69904_2
  - spglib=1.16.5=py39hd257fcd_0
  - sqlite=3.38.5=h4ff8645_0
  - sqlparse=0.4.2=pyhd8ed1ab_0
  - stack_data=0.2.0=pyhd8ed1ab_0
  - svt-av1=1.1.0=h27087fc_1
  - sympy=1.10.1=py39hf3d152e_0
  - tabulate=0.8.9=pyhd8ed1ab_0
  - tbb=2021.5.0=h924138e_1
  - tbb-devel=2021.5.0=h924138e_1
  - tenacity=8.0.1=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - torchaudio=0.11.0=py39_cu113
  - torchvision=0.12.0=py39_cu113
  - tornado=6.1=py39hb9d737c_3
  - tqdm=4.64.0=pyhd8ed1ab_0
  - traitlets=5.2.1.post0=pyhd8ed1ab_0
  - typing-extensions=4.2.0=hd8ed1ab_1
  - typing_extensions=4.2.0=pyha770c72_1
  - tzdata=2022a=h191b570_0
  - uncertainties=3.1.6=pyhd8ed1ab_0
  - unicodecsv=0.14.1=py_1
  - urllib3=1.26.9=pyhd8ed1ab_0
  - utfcpp=3.2.1=ha770c72_0
  - vtk=9.1.0=egl_py39h3374e66_8
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - werkzeug=2.1.2=pyhd8ed1ab_1
  - wheel=0.37.1=pyhd8ed1ab_0
  - x264=1!161.3030=h7f98852_1
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xtb=6.5.0=h9d67668_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.11=h166bdaf_1014
  - zstd=1.5.2=h8a70e8d_1
  - pip:
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.0
    - cclib==1.7.1
    - defusedxml==0.7.1
    - django-debug-toolbar==3.4.0
    - django-extensions==3.1.5
    - e3fp==1.2.3
    - fastjsonschema==2.15.3
    - ipykernel==6.15.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jq==1.2.2
    - jsonschema==4.5.1
    - jupyter==1.0.0
    - jupyter-console==6.4.3
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.0
    - mistune==0.8.4
    - mmh3==3.0.0
    - nbclient==0.6.3
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nglview==3.0.3
    - notebook==6.4.11
    - pandocfilters==1.5.0
    - periodictable==1.6.1
    - prometheus-client==0.14.1
    - psutil==5.9.1
    - pyrsistent==0.18.1
    - qtconsole==5.3.0
    - qtpy==2.1.0
    - rest-framework-generic-relations==2.1.0
    - sdaxen-python-utilities==0.1.4
    - seaborn==0.11.2
    - send2trash==1.8.0
    - soupsieve==2.3.2.post1
    - svgwrite==1.4.2
    - terminado==0.15.0
    - tinycss2==1.1.1
    - webencodings==0.5.1
    - widgetsnbextension==3.6.0
prefix: /home/saxelrod/miniconda3/envs/barriers_old
